package eu.kanade.tachiyomi.extension.ko.jjaptoon

import eu.kanade.tachiyomi.network.GET
import eu.kanade.tachiyomi.source.model.*
import eu.kanade.tachiyomi.source.online.ParsedHttpSource
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.Request
import org.jsoup.nodes.Document
import org.jsoup.nodes.Element

class Jjaptoon : ParsedHttpSource() {

    override val name = "짭툰"
        override val baseUrl = "https://www.jjaptoon003.com"
            override val lang = "ko"
                override val supportsLatest = true

                    override fun headersBuilder() = super.headersBuilder()
                            .add("Referer", baseUrl)
                                    .add("Accept-Language", "ko-KR,ko;q=0.9")

                                        override fun popularMangaRequest(page: Int) =
                                                GET("$baseUrl/comics?page=$page", headers)

                                                    override fun popularMangaSelector() = "a[href*='/comics/']:has(img)"

                                                        override fun popularMangaFromElement(element: Element) = SManga.create().apply {
                                                                setUrlWithoutDomain(element.attr("href"))
                                                                        title = element.select("img").attr("alt")
                                                                                    .ifBlank { element.select("span, div, p").firstOrNull { it.text().isNotBlank() }?.text() ?: "" }
                                                                                            thumbnail_url = element.select("img").attr("abs:src")
                                                                                                }

                                                                                                    override fun popularMangaNextPageSelector() = "a[rel=next]"

                                                                                                        override fun latestUpdatesRequest(page: Int) =
                                                                                                                GET("$baseUrl/comics?sort=latest&page=$page", headers)

                                                                                                                    override fun latestUpdatesSelector() = popularMangaSelector()
                                                                                                                        override fun latestUpdatesFromElement(e: Element) = popularMangaFromElement(e)
                                                                                                                            override fun latestUpdatesNextPageSelector() = popularMangaNextPageSelector()

                                                                                                                                override fun searchMangaRequest(page: Int, query: String, filters: FilterList): Request {
                                                                                                                                        val url = "$baseUrl/comics".toHttpUrl().newBuilder()
                                                                                                                                                    .addQueryParameter("search", query)
                                                                                                                                                                .addQueryParameter("page", page.toString())
                                                                                                                                                                            .build()
                                                                                                                                                                                    return GET(url, headers)
                                                                                                                                                                                        }

                                                                                                                                                                                            override fun searchMangaSelector() = popularMangaSelector()
                                                                                                                                                                                                override fun searchMangaFromElement(e: Element) = popularMangaFromElement(e)
                                                                                                                                                                                                    override fun searchMangaNextPageSelector() = popularMangaNextPageSelector()

                                                                                                                                                                                                        override fun mangaDetailsParse(document: Document) = SManga.create().apply {
                                                                                                                                                                                                                title = document.selectFirst("h1")?.text() ?: ""
                                                                                                                                                                                                                        thumbnail_url = document.selectFirst("img[src*='storage/covers']")?.attr("abs:src")
                                                                                                                                                                                                                                author = document.selectFirst("p:contains(작가), span:contains(작가)")
                                                                                                                                                                                                                                            ?.text()?.replace(Regex("작가:?\\s*"), "")?.trim()
                                                                                                                                                                                                                                                    description = document.selectFirst(".whitespace-pre-line, .prose, p.mt-4")?.text()
                                                                                                                                                                                                                                                            status = when {
                                                                                                                                                                                                                                                                        document.body().text().contains("완결") -> SManga.COMPLETED
                                                                                                                                                                                                                                                                                    document.body().text().contains("연재") -> SManga.ONGOING
                                                                                                                                                                                                                                                                                                document.body().text().contains("휴재") -> SManga.ON_HIATUS
                                                                                                                                                                                                                                                                                                            else -> SManga.UNKNOWN
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                            override fun chapterListSelector() = "a[href*='/chapters/']"

                                                                                                                                                                                                                                                                                                                                override fun chapterFromElement(element: Element) = SChapter.create().apply {
                                                                                                                                                                                                                                                                                                                                        setUrlWithoutDomain(element.attr("href"))
                                                                                                                                                                                                                                                                                                                                                name = element.text().trim()
                                                                                                                                                                                                                                                                                                                                                        date_upload = runCatching {
                                                                                                                                                                                                                                                                                                                                                                    element.select("span, time").lastOrNull()?.text()?.let {
                                                                                                                                                                                                                                                                                                                                                                                    java.text.SimpleDateFormat("yyyy-MM-dd", java.util.Locale.KOREAN).parse(it)?.time
                                                                                                                                                                                                                                                                                                                                                                                                } ?: 0L
                                                                                                                                                                                                                                                                                                                                                                                                        }.getOrDefault(0L)
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                override fun pageListParse(document: Document): List<Page> {
                                                                                                                                                                                                                                                                                                                                                                                                                        val imgs = document.select("img[src*='storage'], img[data-src*='storage'], img[src*='chapters']")
                                                                                                                                                                                                                                                                                                                                                                                                                                if (imgs.isNotEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            return imgs.mapIndexed { i, img ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Page(i, "", img.attr("abs:data-src").ifBlank { img.attr("abs:src") })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val snapshot = document.selectFirst("[wire\\:snapshot]")?.attr("wire:snapshot") ?: ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val regex = Regex(""""(https?://[^"]+\.(?:jpg|jpeg|png|webp|gif))"""")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val urls = regex.findAll(snapshot).map { it.groupValues[1] }.toList()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (urls.isNotEmpty()) return urls.mapIndexed { i, url -> Page(i, "", url) }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.select("script").forEach { script ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    val matches = regex.findAll(script.html()).map { it.groupValues[1] }.toList()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (matches.isNotEmpty()) return matches.mapIndexed { i, url -> Page(i, "", url) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return emptyList()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        override fun imageUrlParse(document: Document) = ""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            override fun imageRequest(page: Page) = GET(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    page.imageUrl!!,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headersBuilder().add("Referer", "$baseUrl/").build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }